#!/bin/bash


currentUser="zois"
remote="root@10.10.111.77"
pathToPersonal="/home/zois/Documents/classified/Utilities/todos/personal"
pathToCompany="/home/zois/Documents/classified/Utilities/todos/company"


#########################
#        Colors         #
#########################
ColorOff='\e[0m'     # Color text default
DefaultBd='\e[49m'      # Background color default
Backup='\e[0;31m'       # Red
BackupDim='\e[2;31m'    # Red dim
Internet='\e[0;34m'     # Blue
InternetDim='\e[2;34m'  # Blue dim
Warning='\e[0;36m'      # Cyan
WarningDim='\e[2;36m'   # Cyan dim
User='\e[0;37m'         # White
UserDim='\e[2;37m'      # White dim
UserBold='\e[1;37m'     # White bold
Other='\e[0;90m'    # Dark gray
OtherDim='\e[2;90m' # Dark gray dim
Ender='\e[0;94m' # To do
Error='\e[37;1;41m'     # Red background
Underline='\e[4m' # Underline

trustRemote()
{
	ssh-keygen -t rsa
	ssh $remote mkdir -p .ssh
	cat /home/zois/.ssh/id_rsa.pub | ssh $remote 'cat >> /root/.ssh/authorized_keys'
}

sectionEnd()
{
	printf "${Ender}Section end|" && printf "\u2015%0.s" {1..120} && printf "\n${ColorOff}"
}
