#!/bin/bash
source /home/zois/Documents/Internship/utilities/tools # Include tools in this file. Absolute path to tools.
echo -e "${UserDim}User       |${User} Words...${ColorOff}"
echo -e "${Error}Error      | Words...${DefaultBd}${ColorOff}"
