#!/bin/bash
source /home/zois/Documents/Internship/utilities/tools # Include tools in this file. Absolute path to tools.


while getopts "pcCnr" option; do
	case "${option}" in
		*) optionsArray+=("$option");;
	esac
done
shift $((OPTIND-1))

for val in "${optionsArray[@]}"; do
    echo " - $val"
done
