#!/bin/bash
source /home/zois/Documents/Internship/utilities/tools # Include tools in this file. Absolute path to tools.
source $pTodoFunctions


# Flag parsing.
while getopts "pcCnr" option; do
	case "${option}" in
		p) optionsArray+=("$option") ;;
                c) optionsArray+=("$option") ;;
                C) optionsArray+=("$option") ;;
                n) optionsArray+=("$option") ;;
                r) optionsArray+=("$option") ;;
        esac
done
shift $((OPTIND-1))

if [[ ${#optionsArray[@]} == 1 ]]; then
	if [[ ${optionsArray[0]} == "p" || ${optionsArray[0]} == "c" ]]; then
		displayTodo
	fi
elif [[ ${#optionsArray[@]} == 2 ]]; then
	if [[ "${optionsArray[@]}" =~ "p" ]] && [[ "${optionsArray[@]}" =~ "C" ]]; then
		todoType="personal"
		removeTodo
	elif [[ "${optionsArray[@]}" =~ "C" ]] && [[ "${optionsArray[@]}" =~ "C" ]]; then
		todoType="company"
		removeTodo
	elif [[ "${optionsArray[@]}" =~ "n" ]] && [[ "${optionsArray[@]}" =~ "p" ]]; then
		todoType="personal"
		addTodo
        elif [[ "${optionsArray[@]}" =~ "n" ]] && [[ "${optionsArray[@]}" =~ "c" ]]; then
                : # todo add new company todo.
        elif [[ "${optionsArray[@]}" =~ "r" ]] && [[ "${optionsArray[@]}" =~ "p" ]]; then
                : # todo remove personal todo without completion.
        elif [[ "${optionsArray[@]}" =~ "r" ]] && [[ "${optionsArray[@]}" =~ "c" ]]; then
                : # todo remove company todo without completion.
	fi
fi
