#!/bin/bash
source /home/zois/Documents/classified/Utilities/tools # Include tools in this file. Absolute path to tools.

echo -e "${UserDim}User       |${User} Reading touchpad's id...${ColorOff}"
read TPdevice <<< $( xinput | sed -nre '/TouchPad|Touchpad/s/.*id=([0-9]*).*/\1/p' )
state=$( xinput list-props "$TPdevice" | grep "Device Enabled" | grep -o "[01]$" )

if [ "$state" -eq '1' ];then
	xinput --disable "$TPdevice"
	echo -e "${UserDim}User       |${User} Touchpad  disabled.${ColorOff}"
else
	xinput --enable "$TPdevice"
	echo -e "${UserDim}User       |${User} Touchpad enabled.${ColorOff}"
fi

