#!/bin/bash
source /home/zois/Documents/classified/Utilities/tools  # Include tools in this file. Absolute path to tools.


scp $pTools $remote:
scp $pUpdater $remote:
ssh $remote ./updater
wait
ssh $remote rm tools
ssh $remote rm updater
